### ISSUE TITLE
Nette/Object with Kdyby/Events

### ISSUE THREAD

**Issue by simPod** [Kdyby/Events#106]
I somehow noticed nette is getting rid of Nette/Object. So I started to use SmartObject trait with this library instead. But is it good approach? It' weird to me that I use SmartObject just to be able to use this library...

**Comment by enumag** [comment]
I don't think you need SmartObject. Kdyby/Events identifies the properties by their "on" prefix (I think). You don't need smart object for that. The only thing you'll need is a helper function to invoke all functions in the array.

**Comment by TomasVotruba** [comment]
@simPod Do you still need help?

**Comment by simPod** [comment]
No, I'm good, thanks everyone!

I also realised I'd rather use eventmanager to dispatch events.

**Comment by TomasVotruba** [comment]
@simPod Great. How does it look like in full-code version?

If really solved, please close the issue.

**Comment by simPod** [comment]
Most of the events I try to dispatch using 
```
$this->evm->dispatchEvent(
	Event::SOMENAME,
	new EventArgsList(...$args)
);
```

**Comment by TomasVotruba** [comment]
Great, that's the best way I could think of.
