### ISSUE TITLE
Problem with onClear event

### ISSUE THREAD

**Issue by martinknor** [Kdyby/Events#109]
A function `\Doctrine\ORM\Internal\Hydration\AbstractHydrator::cleanup` call `->removeEventListener([Events::onClear], $this);`, but this failed at `\Kdyby\Events\EventManager:218`

PHP Notice: Undefined index: Doctrine\ORM\Event::onClear in ...\vendor\kdyby\events\src\Events\EventManager.php:218

**Comment by kocourPB** [comment]
i got same problem

**Comment by aleswita** [comment]
I have same issue after update some doctrine libraries..

My proactional solution:
$ composer require doctrine/common:~2.7.0
$ composer require doctrine/dbal:~2.5.0
$ composer require doctrine/orm:2.5.6

**Comment by hubipe** [comment]
Same problem here, problem caused in doctrine/orm v2.5.7. Version 2.5.6 works fine.

**Comment by JanGalek** [comment]
https://github.com/Kdyby/Events/pull/110 this will fix a problem

**Comment by petrparolek** [comment]
fixed by https://github.com/doctrine/doctrine2/releases/tag/v2.5.9
