### ISSUE TITLE
Nette\PhpGenerator\Method::setBody(): Argument #1 ($code) must be of type string, null given, called in vendor\kdyby\events\src\Events\DI\EventsExtension.php on line 185 

### ISSUE THREAD

**Issue by Honzy** [Kdyby/Events#130]
Zdravim, 

pri aktualizaci nette/di v3.0.12 -> v3.0.13 vyskoci TypeError: Nette\PhpGenerator\Method::setBody(): Argument #1 ($code) must be of type string, null given, called in vendor\kdyby\events\src\Events\DI\EventsExtension.php on line 185 

Staci prepsat _$init->setBody(NULL); -> $init->setBody('');_, ale toto mi neprislo jako spravne reseni, takze misto PR volim radeji new isssue.

Dekuji za opravu.

**Comment by Spamercz** [comment]
Koukali jsme na to a přijde mi že se to snaží vynulovat body což se docílí právě tím co píšeš, tak asi dobrý viz #131
