### ISSUE TITLE
replace method_exists per is_callable

### ISSUE THREAD

**Issue by sneznaovca** [Kdyby/Events#57]
What do you think about replace method_exists per is_callable?
https://github.com/Kdyby/Events/blob/master/src/Kdyby/Events/EventManager.php#L194 

http://cz1.php.net/manual/en/function.method-exists.php see notes
is_callable allows use __call

**Comment by fprochazka** [comment]
Solved with https://github.com/Kdyby/Events/compare/69806d1a...b6fc86b6
