### ISSUE TITLE
Weird order of event listeners

### ISSUE THREAD

**Issue by enumag** [Kdyby/Events#65]
I use Kdyby/Events dev-master, not stable.

I've an event in one of my components:

```php
class FooFormControl extends Control
{
	/** @var callable[] */
	public $onSuccess;
	//...
}
interface IFooFormFactory
{
	/** @return FooFormControl */
	public function create();
}
```

In presenter I create the component using a generated factory and bind a callback function:

```php
class FooPresenter extends BasePresenter
{
	public function actionDefault($id)
	{
		//...
		$this->getComponent('form')->onSuccess[] = function () {
			$this->flashMessage('...');
			$this->redirect('Homepage:');
		};
	}
	protected function createComponentForm(IFooFormFactory $factory)
	{
		return $factory->create();
	}
}
```

I also have a listener:

```php
class FooListener extends Object implements Subscriber
{
	public function getSubscribedEvents()
	{
		return [
			'FooFormControl::onSuccess' => 'fooSuccess',
		];
	}
	public function fooSuccess()
	{
		//...
	}
}
```

Turns out that the listener is never called because the callback from presenter is executed first and the redirect shut's down the application. I expected the listener to be executed first because it was added first (by the generated code in generated factory) and the callback from presenter was added later.

When I remove the redirect, the listener is indeed executed, I checked that.

Is this a bug or a feature? Or am I missing something?

Or should I use a different approach? If so can you suggest? :-)

**Comment by fprochazka** [comment]
It's feature, but you're not the first one reporting this.

**Comment by enumag** [comment]
In that case, how should I fix my application? I'm not sure what it the intended solution.

**Comment by fprochazka** [comment]
I think we should come up with a solution :)

**Comment by enumag** [comment]
Well I'd suggest something like:

```
/**
 * @var callable[]
 * @lazy
 */
public $onSuccess;
```

But I might be missing something and am not sure about the annotation either. Also it needs to be compile-time so Kdyby/Annotations are probably out of the question here.

**Comment by enumag** [comment]
Another thing to consider is adding an option to DI extension to make this behaviour default.

**Comment by fprochazka** [comment]
I had the exactly same thought :)

**Comment by enumag** [comment]
:-) Maybe `@globalEventsFirst` & `@globalEventsLast`?

**Comment by enumag** [comment]
@fprochazka I looked into https://github.com/Kdyby/Events/commit/7abbbd825144b5e0ccdc0b6700509cfabf970245 a bit more and it seems there are some unrelated changes as well - two lines refactored in the Event class (those should be commited regardless) and also some changes in EventManager which I don't understand - can you explain what the EM changes are for? They are unrelated right?

I might use the rest to prepare a PR when I get bored. :-))

**Comment by fprochazka** [comment]
@enumag yes, there are unrelated changes, because I started a bit bigger refactoring that should have included some more speed optimizations - but haven't finished it obviousely.
