### ISSUE TITLE
Add support for something like EventObject in dispatchEvent method

### ISSUE THREAD

**Issue by icaine** [Kdyby/Events#76]
I would like to use something similar to `$em->dispatchEvent(new App\Events\StartupEvent(...))` instead of `$em->dispatchEvent('app.startup', ...)` . Because this way i dont have to remeber exact "string" name of the event and what parameters/arguments i need.

It also may be easily implemented to dispatchEvent method:

``` php
if ($eventName instanceof Kdyby\Events\EventObject) {
    $eventArgs = new EventArgsList(array($eventName));
    $eventName = get_class($eventName);
}
```

What do you think about it?

**Comment by fprochazka** [comment]
On the first look, I really like the idea, but I'm not sure if there aren't any non-obviouse design issues with it.

**Comment by newPOPE** [comment]
+1

Maybe `new App\Events\StartupEvent(...)` is not good example, I like something like `new App\Events\AppStartupEvent(...)` or `new PostCommentedEvent(...)`...

**Comment by enumag** [comment]
I can see one problem. The EVM would probably hold a map like `[ classname => array_of_listeners ]`. Imagine you would want to add some parameters to a existing event - you would extend the event class and add some properties and methods to it. But the extended class would not work because its class name won't be in the map.

**Comment by klimesf** [comment]
+1 for the idea, events can be more than just data. Great move towards OOP.
+1 for `EventObjectInterface::getEventName()`.

**Comment by enumag** [comment]
Another note: performance - this might be bad for events that can occur many times during one request, especially if there is no listener for them

**Comment by icaine** [comment]
It is on the programmer to decide whether to use objects or simple arrays. Otherwise we still use the fastest plain PHP.. :)

**Comment by solcik** [comment]
+1

**Comment by fprochazka** [comment]
@enumag actually, EVM already considers [inheritance](https://github.com/Kdyby/Events/blob/e6bd5d49e29118af3c6038a8939bd0763c65b211/src/Kdyby/Events/EventManager.php#L323).

**Comment by enumag** [comment]
@fprochazka I know but that's for listeners, this is different.

**Comment by foxycode** [comment]
+1

**Comment by fprochazka** [comment]
I would love to implement this, but it would be out-of-scope. https://github.com/Kdyby/Events/issues/97#issuecomment-301213842
