### ISSUE TITLE
ErrorException when rendering previous requests

### ISSUE THREAD

**Issue by PavelJurasek** [Kdyby/Events#78]
List of listeners doesn't render properly when displaying events from previous requests.
Ends up with:

Error: Kdyby\Events\Diagnostics\Panel
exception 'ErrorException' with message 'Argument 1 passed to Kdyby\Events\Diagnostics\Panel::Kdyby\Events\Diagnostics\{closure}() must be an instance of Nette\Reflection\GlobalFunction, instance of Nette\Reflection\Method given, called in .../vendor/kdyby/events/src/Kdyby/Events/Diagnostics/Panel.php on line 405 and defined' in .../vendor/kdyby/events/src/Kdyby/Events/Diagnostics/Panel.php:391

Version 2.4.0 for Nette 2.3

**Comment by matej21** [comment]
It is fixed in master

**Comment by fprochazka** [comment]
Fixed in https://github.com/Kdyby/Events/pull/73
