### ISSUE TITLE
Bad argument given to Panel with kdyby/ElasticSearch

### ISSUE THREAD

**Issue by legendik** [Kdyby/Events#83]
Hi @fprochazka,

I'm using `events` with `kdyby/ElasticSearch` on one project, but when i search something with Elastic, i get following error and any other listener isn't called :( I'm not sure if this is bug in events or elasticsearch. Here is some error message with screen:
```
exception 'ErrorException' with message 'Argument 1 passed to Kdyby\Events\Diagnostics\Panel::Kdyby\Events\Diagnostics\{closure}() must be an instance of Nette\Reflection\GlobalFunction, instance of Nette\Reflection\Method given, called in /Users/legendik/work/srovnavac/vendor/kdyby/events/src/Kdyby/Events/Diagnostics/Panel.php on line 405 and defined' in /Users/legendik/work/srovnavac/vendor/kdyby/events/src/Kdyby/Events/Diagnostics/Panel.php:391
Stack trace:
#0 /Users/legendik/work/srovnavac/vendor/kdyby/events/src/Kdyby/Events/Diagnostics/Panel.php(391): Tracy\Debugger::errorHandler(4096, 'Argument 1 pass...', '/Users/legendik...', 391, Array)
#1 /Users/legendik/work/srovnavac/vendor/kdyby/events/src/Kdyby/Events/Diagnostics/Panel.php(405): Kdyby\Events\Diagnostics\Panel->Kdyby\Events\Diagnostics\{closure}(Object(Nette\Reflection\Method))
#2 /Users/legendik/work/srovnavac/vendor/kdyby/events/src/Kdyby/Events/Diagnostics/Panel.php(236): Kdyby\Events\Diagnostics\Panel->renderListeners(Array)
#3 /Users/legendik/work/srovnavac/vendor/kdyby/events/src/Kdyby/Events/Diagnostics/Panel.php(203): Kdyby\Events\Diagnostics\Panel->renderPanelDispatchLog(Array)
#4 /Users/legendik/work/srovnavac/vendor/tracy/tracy/src/Tracy/Bar.php(73): Kdyby\Events\Diagnostics\Panel->getPanel()
#5 /Users/legendik/work/srovnavac/vendor/tracy/tracy/src/Tracy/Debugger.php(207): Tracy\Bar->render()
#6 [internal function]: Tracy\Debugger::shutdownHandler()
#7 {main}
```
<img width="791" alt="screen shot 2015-10-19 at 21 45 13" src="https://cloud.githubusercontent.com/assets/2327491/10589338/10519c94-76ab-11e5-938b-cb8485b64888.png">

I'm using both libraries in dev version.

BTW, Tracy isn't generated, just this :(

**Comment by fprochazka** [comment]
@legendik hi, what version are you using? Can you try master?

**Comment by legendik** [comment]
I've had this in `composer.json`
```yml
"kdyby/doctrine": "~3.0@dev",
"doctrine/search": "dev-devel",
"kdyby/doctrine-search": "dev-master",
"kdyby/elastic-search": "dev-master",
```

`"kdyby/doctrine": "~3.0@dev"` probably installed `master` version of `kdyby/events`. But after update `kdyby/events` to `@dev` its all fixed :-)

Thanks for youre time. I think you can close this issue (and maybe update dependency on `kdyby/events` in `kdyby/doctrine`?)

**Comment by fprochazka** [comment]
@legendik dev dependencies are not installed recursively. You can check what you have installed using `composer show --installed`.

I'm going to tag this soon-ish and that should resolve it.
