### ISSUE TITLE
Listeners on generated forms

### ISSUE THREAD

**Issue by george-oakling** [Kdyby/Events#84]
Lets say I have a form, which is generated like below. How could I add listeners for onSuccess on this type of form? Thanks a lot :)

```php
class SpecialForm extends Nette\Object {
   public function create() {
     $form = new UI\Form;
     return $form;
   }
}

class SpecialPresenter {

   /** @inject */
   public $specialForm;

   protected function createComponentSpecialForm() {
      return $this->specialForm->create();
   }
}
```

**Comment by fprochazka** [comment]
Hi, technically, you can. But this lib is not able to autowire a thing like that. You'd have to wire them by hand

```php
class SpecialForm extends Nette\Object {
   private $evm;
   public function __construct(EventManager $evm) { $this->evm = $evm; }

   public function create() {
     $form = new UI\Form;
     $form->onSuccess = $this->evm->createEvent([get_class($form), 'onSuccess']);
     // ...
     return $form;
   }
}
```

But your example does not contain a generated form, but rather created by a custom factory. If you really create the form using [generated factory](https://pla.nette.org/cs/create-components-with-autowiring), this lib should be able to autowire it.

**Comment by george-oakling** [comment]
Thanks a lot, it was much easier to change the logic to standard generated factory and it is working now as expected.
