### ISSUE TITLE
Compatibility with Symfony 3.0

### ISSUE THREAD

**Issue by hrach** [Kdyby/Events#89]
Class Kdyby\Events\SymfonyDispatcher contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\EventDispatcher\EventDispatcherInterface::getListenerPriority).

Workaround: add version constraint to own composer.json.

**Comment by achtan** [comment]
+1

**Comment by artemevsin** [comment]
+1

**Comment by enumag** [comment]
Just like most of the other methods this should probably just throw a NotSupportedException right?

**Comment by lukasojd** [comment]
++

**Comment by lukasojd** [comment]
Workaround: you must add "symfony/event-dispatcher": "~2.8.2" to you your composer.json

**Comment by enumag** [comment]
@fprochazka Do you plan to actually implement that new getListenerPriority method (and not throw a NotSupportedException)? I don't see any benefit in it.

**Comment by fprochazka** [comment]
Should be solved with https://github.com/Kdyby/Events/commit/de3cdc4b6e16051ff76c6a1e9472227dd0facab5.
