### ISSUE TITLE
Add CoC document

### ISSUE THREAD

**Issue by nobodyguy** [Kdyby/Events#91]
This project should include Code-of-conduct document to explicitly express that it is open to diversity.
If you don't want it, you are evil. Evil right down to your cold black heart, which pump not blood like mine, but rather a thick, vomitous oil that oozes through your rotten veins and clots in your pea-sized brain which becomes the cause of your Nazi-esque patterns of violent behavior. Do you understand?

Thanks!

**Comment by fprochazka** [comment]
![at least it s not raining](https://cloud.githubusercontent.com/assets/158625/12533794/f7032900-c23c-11e5-94a8-9db3cc0d5c1b.gif)

**Comment by fprochazka** [comment]
:heart:
