### ISSUE TITLE
Full Symfony EventDispatcher's support (with EventSubscriberInterface)

### ISSUE THREAD

**Issue by hranicka** [Kdyby/Events#92]
Maybe this refs to #89 

Currently, only **Doctrine Events** are fully supported.

They're supported **Symfony Events** too, but only partially. [Event dispatching only](https://github.com/Kdyby/Events/blob/master/src/Kdyby/Events/SymfonyDispatcher.php).

My problem:

I want to use Symfony Console + Monolog + Symfony Monolog Bridge.
It's realized via [this subscriber](https://github.com/symfony/monolog-bridge/blob/master/Handler/ConsoleHandler.php).

But I cannot register this subscriber (eg. with tags in config). **It's not a Doctrine EventSubscriber**.

I've made another extension of Kdyby/Events extension:
https://github.com/etten/symfony-events

---

Should I create a PR to this repo for full built-in support of Symfony Events?

I think a lot of changes will be needed - the Symfony EventSubscriber requires static method and carries information about event name, handler method and priority.

**Comment by enumag** [comment]
@hranicka What about https://github.com/Symnedi/EventDispatcher?

**Comment by fprochazka** [comment]
I'm gonna have to think about this more, but I'm not sure full support of `symfony/event-dispatcher` is a good way. See #97

**Comment by fprochazka** [comment]
I've decided - I wanna drastically simplify this package, so adding full support for symfony dispatcher is not doable, sorrry.
